# Generated by Django 2.1 on 2019-12-04 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRecetaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechanacimiento', models.DateField()),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True, null=True)),
                ('fk_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Especie')),
                ('fk_generomascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.GeneroMascota')),
            ],
        ),
        migrations.CreateModel(
            name='MedicoVeterinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fechanacimiento', models.DateField()),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('correoelectronico', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True, null=True)),
                ('celular', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('is_usuario', 'Is Usuario'), ('is_admin', 'Is Admin'), ('is_medico', 'Is Medico')),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('fk_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Mascotas')),
                ('fk_medicoveterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.MedicoVeterinaria')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fechanacimiento', models.DateField()),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('correoelectronico', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True, null=True)),
                ('celular', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('logo', models.CharField(max_length=40)),
                ('correocoorporativo', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True, null=True)),
                ('telefono', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='fk_veterinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Veterinaria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fk_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.TipoProducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fk_veterinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Veterinaria'),
        ),
        migrations.AddField(
            model_name='medicoveterinaria',
            name='fk_veterinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Veterinaria'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='fk_raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Raza'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Usuario'),
        ),
        migrations.AddField(
            model_name='detallerecetamedica',
            name='fk_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.TipoProducto'),
        ),
        migrations.AddField(
            model_name='detallerecetamedica',
            name='fk_recetamedica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.RecetaMedicas'),
        ),
    ]
