# Generated by Django 2.1 on 2019-12-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlesMedicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('observacion', models.CharField(max_length=250)),
                ('proximadesControl', models.DateField()),
                ('numeroRegistro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInfoVacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRecetaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicaciones', models.CharField(max_length=60)),
                ('observaciones', models.CharField(max_length=200)),
                ('fk_ControlMedico', models.ForeignKey(db_column='fk_ControlMedico', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.ControlesMedicos')),
            ],
        ),
        migrations.CreateModel(
            name='Efectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[(1, 'Hombre'), (2, 'Mujer')], default=1, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[(1, 'Macho'), (2, 'Hembra')], default=1, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='InfoDesparacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('proximadesparacitante', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoVacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('proximavacuna', models.DateField()),
                ('numeroregistro', models.IntegerField()),
                ('sticker', models.ImageField(blank=True, null=True, upload_to='Images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechanacimiento', models.DateField()),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Images/%Y')),
                ('fk_especie', models.ForeignKey(db_column='fk_especie', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Especie')),
                ('fk_generomascota', models.ForeignKey(db_column='fk_generomascota', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.GeneroMascota')),
            ],
        ),
        migrations.CreateModel(
            name='MedicoVeterinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fechanacimiento', models.DateField()),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('correoelectronico', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
                ('celular', models.CharField(max_length=40)),
                ('fk_genero', models.ForeignKey(db_column='fk_genero', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('is_usuario', 'Is Usuario'), ('is_admin', 'Is Admin'), ('is_medico', 'Is Medico')),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_infovacuna', models.ForeignKey(db_column='fk_infovacuna', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.InfoVacunas')),
                ('fk_mascota', models.ForeignKey(db_column='fk_mascota', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Mascotas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[(1, 'Comida'), (2, 'Medicamentos'), (3, 'Aseo')], default=1, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fechanacimiento', models.DateField()),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('correoelectronico', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
                ('celular', models.CharField(max_length=40)),
                ('fk_genero', models.ForeignKey(db_column='fk_genero', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('logo', models.CharField(max_length=40)),
                ('correocoorporativo', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
                ('telefono', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='fk_veterinaria',
            field=models.ForeignKey(db_column='fk_veterinaria', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Veterinaria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fk_Tipoproducto',
            field=models.ForeignKey(db_column='fk_Tipoproducto', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.TipoProducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fk_veterinaria',
            field=models.ForeignKey(db_column='fk_veterinaria', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Veterinaria'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Usuario'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='fk_recordatorios',
            field=models.ForeignKey(db_column='fk_recordatorios', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Recordatorios'),
        ),
        migrations.AddField(
            model_name='medicoveterinaria',
            name='fk_veterinaria',
            field=models.ForeignKey(db_column='fk_veterinaria', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Veterinaria'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='fk_raza',
            field=models.ForeignKey(db_column='fk_raza', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Raza'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Usuario'),
        ),
        migrations.AddField(
            model_name='infovacunas',
            name='fk_mascota',
            field=models.ForeignKey(db_column='fk_mascota', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Mascotas'),
        ),
        migrations.AddField(
            model_name='infovacunas',
            name='fk_producto',
            field=models.ForeignKey(db_column='fk_producto', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Producto'),
        ),
        migrations.AddField(
            model_name='infodesparacitacion',
            name='fk_mascota',
            field=models.ForeignKey(db_column='fk_mascota', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Mascotas'),
        ),
        migrations.AddField(
            model_name='infodesparacitacion',
            name='fk_producto',
            field=models.ForeignKey(db_column='fk_producto', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Producto'),
        ),
        migrations.AddField(
            model_name='detallerecetamedica',
            name='fk_producto',
            field=models.ForeignKey(db_column='fk_producto', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Producto'),
        ),
        migrations.AddField(
            model_name='detalleinfovacunas',
            name='fk_efecto',
            field=models.ForeignKey(db_column='fk_efecto', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Efectos'),
        ),
        migrations.AddField(
            model_name='detalleinfovacunas',
            name='fk_infovacuna',
            field=models.ForeignKey(db_column='fk_infovacuna', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.InfoVacunas'),
        ),
        migrations.AddField(
            model_name='controlesmedicos',
            name='fk_mascota',
            field=models.ForeignKey(db_column='fk_mascota', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Mascotas'),
        ),
        migrations.AddField(
            model_name='controlesmedicos',
            name='fk_medicoveterinario',
            field=models.ForeignKey(db_column='fk_medicoveterinario', on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.MedicoVeterinaria'),
        ),
    ]
