# Generated by Django 2.1 on 2019-12-04 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPetQR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleInfoVacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InfoDesparacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('proximadesparacitante', models.DateField()),
                ('fk_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Mascotas')),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='InfoVacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('proximavacuna', models.DateField()),
                ('fk_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Mascotas')),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=40)),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_infovacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.InfoVacunas')),
                ('fk_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Mascotas')),
            ],
        ),
        migrations.AddField(
            model_name='sticker',
            name='lote',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallerecetamedica',
            name='fk_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Producto'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='fk_recordatorios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Recordatorios'),
        ),
        migrations.AddField(
            model_name='detalleinfovacunas',
            name='fk_infovacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.InfoVacunas'),
        ),
        migrations.AddField(
            model_name='detalleinfovacunas',
            name='fk_sticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Sticker'),
        ),
    ]
