# Generated by Django 2.1 on 2019-12-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPetQR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='foto',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
