# Generated by Django 2.1 on 2019-12-13 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPetQR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlesmedicos',
            name='numeroRegistro',
        ),
        migrations.RemoveField(
            model_name='infovacunas',
            name='numeroregistro',
        ),
        migrations.AddField(
            model_name='raza',
            name='fk_especie',
            field=models.ForeignKey(db_column='fk_especie', default=1, on_delete=django.db.models.deletion.CASCADE, to='AppPetQR.Especie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(default=1, max_length=40),
        ),
        migrations.AlterField(
            model_name='generomascota',
            name='nombre',
            field=models.CharField(default=1, max_length=40),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
