# Generated by Django 2.1 on 2019-12-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPetQR', '0002_auto_20191213_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallerecetamedica',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='detallerecetamedica',
            name='indicaciones',
            field=models.CharField(max_length=200),
        ),
    ]
