# Generated by Django 2.1 on 2019-12-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPetQR', '0002_auto_20191209_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='foto',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
