# Generated by Django 2.0 on 2019-12-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPetQR', '0002_auto_20191203_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medicoveterinaria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
