# Generated by Django 2.1 on 2019-12-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPetQR', '0003_auto_20191204_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='foto',
            field=models.ImageField(default=None, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
