# Generated by Django 2.1 on 2019-12-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPetQR', '0003_auto_20191210_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%n/%d/'),
        ),
    ]
