# Generated by Django 2.1 on 2019-12-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPetQR', '0004_auto_20191210_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleinfovacunas',
            name='fk_sticker',
        ),
        migrations.AddField(
            model_name='infovacunas',
            name='sticker',
            field=models.ImageField(blank=True, null=True, upload_to='sticker/%Y/%n/%d/'),
        ),
        migrations.DeleteModel(
            name='Sticker',
        ),
    ]
