# Generated by Django 2.1 on 2019-12-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPetQR', '0005_auto_20191211_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infovacunas',
            name='sticker',
            field=models.ImageField(blank=True, null=True, upload_to='sticker/%Y'),
        ),
    ]
