# Generated by Django 2.1 on 2019-12-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPetQR', '0007_auto_20191211_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infovacunas',
            name='sticker',
            field=models.ImageField(blank=True, null=True, upload_to='Images/%Y/%n/%d'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Images/%Y/%n/%d/'),
        ),
    ]
